//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayDrone2SQL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class App
    {
        public System.Guid Id { get; set; }
        public string AppId { get; set; }
        public string Title { get; set; }
        public string DeveloperName { get; set; }
        public System.Guid Category { get; set; }
        public bool Free { get; set; }
        public long VersionCode { get; set; }
        public string VersionString { get; set; }
        public long InstallationSize { get; set; }
        public long Downloads { get; set; }
        public double StarRating { get; set; }
        public System.DateTime SnapshotDate { get; set; }
        public string MetadataUrl { get; set; }
        public string ApkUrl { get; set; }
    
        public virtual Category Category1 { get; set; }
    }
}
